import "server-only";
import { timingSafeEqual, scrypt as scryptCallback } from "node:crypto";
import { promisify } from "node:util";
import { getServerEnv } from "@/lib/env/server";
const scrypt=promisify(scryptCallback); const MAX_PASSWORD_LENGTH=1024;
/** Verifies the configured server-side hash. Argon2id is required in production. */
export async function verifySitePassword(password:string){if(!password||password.length>MAX_PASSWORD_LENGTH)return false; try { const hash=getServerEnv().SITE_PASSWORD_HASH;
 if(hash.startsWith("$argon2id$")){ const loader=(0,eval)("require") as (name:string)=>{verify:(hash:string,password:string)=>Promise<boolean>}; const argon2=loader("@node-rs/argon2"); return await argon2.verify(hash,password); }
 // A deliberately documented local-development fallback, never generated by the setup script.
 const [kind,salt,encoded]=hash.split("$"); if(kind!=="scrypt"||!salt||!encoded)return false; const actual=Buffer.from(await scrypt(password,salt,64) as Buffer); const expected=Buffer.from(encoded,"base64url"); return actual.length===expected.length&&timingSafeEqual(actual,expected);
 }catch{return false}}
