"use client";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { CalendarDays, Camera, ChevronDown, Coffee, Flower2, Heart, Music2, Sparkles, Trees, Utensils, Check } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { bucketListCategories } from "@/data/loveStory";
import { motionTokens } from "@/lib/motion";
type Filter = "all" | "completed" | "open";
const STORAGE_KEY = "nadia-jakob-bucket-list-completed", EXPANDED_KEY = "nadia-jakob-bucket-list-expanded";
const icons = { heart: Heart, sparkles: Sparkles, utensils: Utensils, trees: Trees, music: Music2, flower: Flower2, calendar: CalendarDays, camera: Camera, coffee: Coffee };
export default function BucketList({locale="de"}:{locale?:"de"|"pl"}) {
 const [completed,setCompleted]=useState<string[]>([]),[expanded,setExpanded]=useState<string[]>([bucketListCategories[0].id,bucketListCategories[1].id]),[filter,setFilter]=useState<Filter>("all"),[hydrated,setHydrated]=useState(false); const reduced=useReducedMotion(); const allItems=useMemo(()=>bucketListCategories.flatMap(c=>c.items),[]); const completedSet=new Set(completed); const done=allItems.filter(i=>completedSet.has(i.id)).length; const percent=Math.round(done/allItems.length*100);
 useEffect(()=>{const timer=window.setTimeout(()=>{try { const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)??"[]"), open=JSON.parse(localStorage.getItem(EXPANDED_KEY)??"null"); if(Array.isArray(saved))setCompleted(saved);if(Array.isArray(open))setExpanded(open);}catch{}setHydrated(true)},0);return()=>clearTimeout(timer)},[]);
 useEffect(()=>{if(hydrated)localStorage.setItem(STORAGE_KEY,JSON.stringify(completed))},[completed,hydrated]); useEffect(()=>{if(hydrated)localStorage.setItem(EXPANDED_KEY,JSON.stringify(expanded))},[expanded,hydrated]);
 const toggle=(id:string)=>setCompleted(cur=>cur.includes(id)?cur.filter(x=>x!==id):[...cur,id]);
 const plActivities: Record<string,string[]> = {
  dates:["Pójść razem do kina","Pójść na lody","Pójść razem na kawę lub kakao","Wybrać się na wspólny spacer","Zrobić piknik","Pójść razem coś zjeść","Zrobić wieczór filmowy","Obejrzeć zachód słońca","Obserwować razem gwiazdy","Obejrzeć wschód słońca","Zaplanować randkę-niespodziankę","Zjeść elegancką kolację","Wyjść na śniadanie","Zrobić śniadanie do łóżka","Spędzić dzień bez telefonów","Wybrać się na nocny spacer","Zaplanować sobie nawzajem cały dzień","Wrócić do miejsca naszej pierwszej randki","Spędzić deszczowy dzień razem w domu","Spędzić spontaniczny wieczór bez planu"],
  adventure:["Pojechać razem nad morze","Spędzić urlop w górach","Wybrać się na spontaniczny weekend","Zrobić roadtrip przez kilka krajów","Obejrzeć wschód słońca w innym kraju","Odwiedzić Bayern-Park","Pojeździć razem na kolejce górskiej","Odwiedzić Europa-Park","Zagrać w kręgle","Zagrać w minigolfa","Pojeździć gokartami","Rozwiązać escape room","Zagrać w laser tag","Odwiedzić park trampolin","Odwiedzić park linowy","Pojechać na letnim torze saneczkowym","Wybrać się w rejs","Odwiedzić zoo lub park zwierząt","Odwiedzić termy","Odwiedzić park rozrywki nocą","Spróbować aktywności, której żadne z nas jeszcze nie robiło","Pojeździć razem na łyżwach","Zrobić wieczór gier","Pograć razem","Wybrać się na spontaniczną jednodniową wycieczkę"],
  food:["Zjeść razem pizzę","Spróbować polskiego jedzenia","Pójść do włoskiej restauracji","Zrobić razem pierogi","Gotować razem","Upiec ciasto","Upiec ciasteczka","Ugotować trzydaniowy posiłek","Zorganizować kolację przy świecach w domu","Wypróbować nową restaurację","Spróbować street foodu","Wyjść razem na śniadanie","Odwiedzić jarmark bożonarodzeniowy","Znaleźć naszą wspólną ulubioną restaurację","Stworzyć nasze wspólne ulubione danie","Ugotować potrawę z kraju, który chcemy odwiedzić","Zorganizować wieczór degustacji w ciemno","Pójść razem na kurs gotowania","Urządzić randkę z nocną przekąską","Ugotować sobie nawzajem ulubione jedzenie"],
  nature:["Wybrać się razem na wędrówkę","Zdobyć górski szczyt","Odwiedzić wodospad","Spędzić czas nad jeziorem","Pojechać razem nad morze","Spacerować po śniegu","Zrobić piknik o zachodzie słońca","Pojechać pod namiot","Spędzić noc pod gwiazdami","Wynająć chatkę w górach","Przejść się boso po plaży","Pojeździć razem na rowerach","Spędzić dzień na łonie natury bez planu","Odwiedzić park narodowy","Odwiedzić punkt widokowy nocą","Spacerować razem w deszczu","Wybrać się na jesienny spacer","Zbierać kwiaty","Ulepić bałwana","Stoczyć bitwę na śnieżki"],
  culture:["Pójść razem na koncert","Odwiedzić kino plenerowe","Obejrzeć musical","Odwiedzić festiwal","Zwiedzić zamek","Odwiedzić muzeum","Obejrzeć wystawę","Pójść na występ komediowy","Odwiedzić jarmark bożonarodzeniowy","Odwiedzić festyn miejski","Odkryć razem nową piosenkę","Stworzyć wspólną playlistę","Spróbować kursu tańca","Pójść na koncert w innym kraju","Zaśpiewać razem karaoke","Obejrzeć wyjątkowy film w kinie","Odwiedzić miejsce historyczne","Wypróbować operę lub spektakl teatralny","Odwiedzić festiwal uliczny","Obejrzeć razem pokaz fajerwerków"],
  wellness:["Pójść razem do term","Zorganizować weekend wellness","Spróbować masażu dla par","Zarezerwować hotel z prywatnym spa","Zrobić dzień dbania o siebie","Wyspać się razem","Nie planować niczego przez cały dzień","Zrobić przytulny wieczór filmowy","Spędzić weekend bez mediów społecznościowych","Pójść razem do sauny","Wybrać się na zimowy urlop z wellness","Spędzić deszczowy dzień z filmami i jedzeniem","Wziąć razem kąpiel z pianą","Wymieniać się masażami","Spędzić spokojny wieczór przy muzyce"],
  seasons:["Świętować naszą rocznicę","Zrobić wspólne zdjęcie bożonarodzeniowe","Stworzyć własną tradycję bożonarodzeniową","Świętować razem Sylwestra","Upiec ciasteczka","Zrobić sobie nawzajem kalendarz adwentowy","Wyrzeźbić dynie","Udekorować choinkę","Spędzić razem Wielkanoc","Wybrać się na wiosenną wycieczkę","Pojechać latem nad jezioro","Spędzić razem jesienny dzień","Wybrać się zimą na ośnieżoną wycieczkę","Odwiedzać co roku nowe miejsce","Napisać w Sylwestra list do naszych przyszłych siebie","Wybierać co roku wspólne ulubione zdjęcie","Spędzać razem urodziny","Stworzyć własną tradycję na naszą rocznicę","Przeżyć razem pierwszy śnieg w roku","Spędzić letni wieczór na zewnątrz"],
  "memories-projects":["Zrobić nasze pierwsze wspólne zdjęcie","Stworzyć wspólny album fotograficzny","Założyć pudełko wspomnień","Rozpocząć album z polaroidami","Stworzyć mapę wszystkich odwiedzonych miejsc","Zrobić wspólny film podsumowujący rok","Stworzyć playlistę na każdy wspólny rok","Napisać listy do przyszłości","Wybierać co miesiąc ulubione zdjęcie","Zrealizować wspólny kreatywny projekt","Stworzyć książkę kucharską z naszymi ulubionymi daniami","Zbierać wspólne żarty i powiedzonka","Zbierać pamiątki z podróży","Stworzyć kapsułę czasu","Prowadzić listę naszych najzabawniejszych chwil","Stworzyć wspólny kalendarz","Stworzyć ścianę ze zdjęciami","Zmontować krótki film o naszym związku","Prowadzić dalej naszą wspólną listę marzeń","Stworzyć stronę internetową o naszej wspólnej historii"],
  everyday:["Chodzić razem na zakupy","Gotować razem","Spędzić cały dzień razem","Sprzątać razem","Długo siedzieć w samochodzie i słuchać muzyki","Rozmawiać do późna w nocy","Zasypiać razem","Wysypiać się razem","Dbać o siebie nawzajem, gdy jedno z nas źle się czuje","Wspólnie kończyć zwykły dzień pracy","Wyskoczyć po spontaniczną przekąskę","Oglądać razem serial","Zrobić razem duże zakupy","Robić sobie nawzajem małe niespodzianki","Uczynić razem nudny dzień pięknym","Odkrywać razem nową muzykę","Wspólnie przeglądać zdjęcia","Stworzyć wspólny plan tygodnia","Przetrwać razem trudny dzień","Po prostu być razem, nie musząc nic robić"],
  romance:["Napisać sobie list miłosny","Obserwować razem gwiazdy","Pocałować się o zachodzie słońca","Pocałować się w deszczu","Zatańczyć powoli w domu","Powiedzieć sobie nawzajem dziesięć rzeczy, które w sobie kochamy","Zrobić niespodziankę w formie prezentu","Przygotować romantyczny wieczór","Czytać razem stare wiadomości","Odtworzyć nasze pierwsze wspólne zdjęcie","Podarować sobie nawzajem playlistę","Odkryć miejsce tylko dla nas","Rozmawiać całą noc o naszej przyszłości","Dać sobie nawzajem odręcznie napisany list","Być przez cały dzień szczególnie uważnymi dla siebie","Wypowiedzieć wspólne marzenie","Zorganizować sobie nawzajem randkę","Zaplanować wyjątkową rocznicę","Świadomie cieszyć się chwilą bez telefonu","Powiedzieć sobie, jaki był nasz najpiękniejszy wspólny moment"]
 };
 const plTitles=["Randki i wspólny czas","Wypoczynek, zabawa i przygody","Jedzenie i przyjemności","Natura i czas na zewnątrz","Kultura, muzyka i wydarzenia","Wellness i relaks","Pory roku i tradycje","Wspomnienia i wspólne projekty","Codzienność i małe chwile","Romantyczne chwile"];
 const text=locale==="pl"?{kicker:"Nasza wspólna lista marzeń",title:"To, czego już doświadczyliśmy – i co jeszcze przed nami.",subtitle:"Nasze wspomnienia, pomysły i wspólne plany w jednym miejscu.",together:"Razem",of:"z",done:"przeżytych chwil",note:"Każdy zaznaczony punkt to mały moment, który możemy zachować.",filters:["Wszystkie","Już przeżyte","Jeszcze przed nami"],reset:"Wyczyść zaznaczenia",empty:"W tej kategorii nie ma jeszcze pozycji dla tego filtra.",wish:"Wspólne marzenie"}:{kicker:"Unsere gemeinsame Bucket List",title:"Was wir schon erlebt haben – und was noch auf uns wartet.",subtitle:"Unsere Erinnerungen, Ideen und gemeinsamen Pläne an einem Ort.",together:"Gemeinsam",of:"von",done:"Erlebnissen schon erlebt",note:"Jeder Haken ist ein kleiner Moment, den wir behalten dürfen.",filters:["Alle","Schon erlebt","Noch offen"],reset:"Haken zurücksetzen",empty:"In dieser Kategorie gibt es für diesen Filter noch keine Einträge.",wish:"Gemeinsamer Wunsch"};
 return <section id="bucket-list" className="section bucket-list" aria-labelledby="bucket-list-title"><p className="kicker">{text.kicker}</p><h2 id="bucket-list-title">{text.title}</h2><p className="bucket-subtitle">{text.subtitle}</p>
 <div className="bucket-overview" aria-label={text.kicker}><div className="progress-orb" style={{"--progress":`${percent * 3.6}deg`} as React.CSSProperties}><strong>{percent}%</strong><span>{text.together}</span></div><div className="overview-copy"><strong>{done} <small>{text.of} {allItems.length}</small></strong><span>{text.done}</span><i><i style={{width:`${percent}%`}}/></i></div><p>{text.note}</p></div>
 <div className="bucket-actions"><div className="bucket-filters" role="group" aria-label={text.kicker}>{(["all","completed","open"] as const).map((value,i)=><button key={value} className={filter===value?"active":""} onClick={()=>setFilter(value)}>{text.filters[i]}</button>)}</div><button className="reset-button" onClick={()=>setCompleted([])} disabled={!completed.length}>{text.reset}</button></div>
 <div className="bucket-categories">{bucketListCategories.map(category=>{const Icon=icons[category.icon as keyof typeof icons];const categoryDone=category.items.filter(i=>completedSet.has(i.id)).length;const visible=category.items.filter((item) => {
        if (filter === "all") return true;
        return filter === "completed" ? completedSet.has(item.id) : !completedSet.has(item.id);
      });const open=expanded.includes(category.id);const categoryIndex=bucketListCategories.indexOf(category);return <article className="bucket-category" key={category.id}><button className="category-heading" onClick={()=>setExpanded(cur=>cur.includes(category.id)?cur.filter(x=>x!==category.id):[...cur,category.id])} aria-expanded={open} aria-controls={`${category.id}-items`}><span className="category-icon"><Icon size={18}/></span><span className="category-copy"><strong>{locale==="pl"?plTitles[categoryIndex]:category.title}</strong><small>{categoryDone} {text.of} {category.items.length} {locale==="pl"?"przeżytych": "erlebt"}</small><i><i style={{width:`${categoryDone/category.items.length*100}%`}}/></i></span><ChevronDown className={open?"chevron open":"chevron"}/></button><AnimatePresence initial={false}>{open&&<motion.div id={`${category.id}-items`} className="bucket-items" initial={reduced?false:{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}} transition={{duration:motionTokens.duration.normal,ease:motionTokens.ease.standard}}>{visible.length?visible.map((item,index)=>{const checked=completedSet.has(item.id);return <motion.label layout className={checked?"bucket-item completed":"bucket-item"} key={item.id}><input type="checkbox" checked={checked} onChange={()=>toggle(item.id)}/><span className="custom-check" aria-hidden="true"><Check size={14}/></span><span>{locale==="pl"?(plActivities[category.id]?.[category.items.indexOf(item)]??`${text.wish} ${category.items.indexOf(item)+1}`):item.text}</span></motion.label>}):<p className="empty-filter">{text.empty}</p>}</motion.div>}</AnimatePresence></article>})}</div></section>
}
