"use client";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { CalendarDays, Camera, ChevronDown, Coffee, Flower2, Heart, Music2, Sparkles, Trees, Utensils, Check } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { bucketListCategories } from "@/data/loveStory";
import { motionTokens } from "@/lib/motion";
type Filter = "all" | "completed" | "open";
const STORAGE_KEY = "nadia-jakob-bucket-list-completed", EXPANDED_KEY = "nadia-jakob-bucket-list-expanded";
const icons = { heart: Heart, sparkles: Sparkles, utensils: Utensils, trees: Trees, music: Music2, flower: Flower2, calendar: CalendarDays, camera: Camera, coffee: Coffee };
export default function BucketList() {
 const [completed,setCompleted]=useState<string[]>([]),[expanded,setExpanded]=useState<string[]>([bucketListCategories[0].id,bucketListCategories[1].id]),[filter,setFilter]=useState<Filter>("all"),[hydrated,setHydrated]=useState(false); const reduced=useReducedMotion(); const allItems=useMemo(()=>bucketListCategories.flatMap(c=>c.items),[]); const completedSet=new Set(completed); const done=allItems.filter(i=>completedSet.has(i.id)).length; const percent=Math.round(done/allItems.length*100);
 useEffect(()=>{const timer=window.setTimeout(()=>{try { const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)??"[]"), open=JSON.parse(localStorage.getItem(EXPANDED_KEY)??"null"); if(Array.isArray(saved))setCompleted(saved);if(Array.isArray(open))setExpanded(open);}catch{}setHydrated(true)},0);return()=>clearTimeout(timer)},[]);
 useEffect(()=>{if(hydrated)localStorage.setItem(STORAGE_KEY,JSON.stringify(completed))},[completed,hydrated]); useEffect(()=>{if(hydrated)localStorage.setItem(EXPANDED_KEY,JSON.stringify(expanded))},[expanded,hydrated]);
 const toggle=(id:string)=>setCompleted(cur=>cur.includes(id)?cur.filter(x=>x!==id):[...cur,id]);
 return <section id="bucket-list" className="section bucket-list" aria-labelledby="bucket-list-title"><p className="kicker">Unsere gemeinsame Bucket List</p><h2 id="bucket-list-title">Was wir schon erlebt haben – und was noch auf uns wartet.</h2><p className="bucket-subtitle">Unsere Erinnerungen, Ideen und gemeinsamen Pläne an einem Ort.</p>
 <div className="bucket-overview" aria-label="Fortschritt der gemeinsamen Bucket List"><div className="progress-orb" style={{"--progress":`${percent * 3.6}deg`} as React.CSSProperties}><strong>{percent}%</strong><span>Gemeinsam</span></div><div className="overview-copy"><strong>{done} <small>von {allItems.length}</small></strong><span>Erlebnissen schon erlebt</span><i><i style={{width:`${percent}%`}}/></i></div><p>Jeder Haken ist ein kleiner Moment, den wir behalten dürfen.</p></div>
 <div className="bucket-actions"><div className="bucket-filters" role="group" aria-label="Bucket List filtern">{([['all','Alle'],['completed','Schon erlebt'],['open','Noch offen']] as const).map(([value,label])=><button key={value} className={filter===value?"active":""} onClick={()=>setFilter(value)}>{label}</button>)}</div><button className="reset-button" onClick={()=>setCompleted([])} disabled={!completed.length}>Haken zurücksetzen</button></div>
 <div className="bucket-categories">{bucketListCategories.map(category=>{const Icon=icons[category.icon as keyof typeof icons];const categoryDone=category.items.filter(i=>completedSet.has(i.id)).length;const visible=category.items.filter((item) => {
        if (filter === "all") return true;
        return filter === "completed" ? completedSet.has(item.id) : !completedSet.has(item.id);
      });const open=expanded.includes(category.id);return <article className="bucket-category" key={category.id}><button className="category-heading" onClick={()=>setExpanded(cur=>cur.includes(category.id)?cur.filter(x=>x!==category.id):[...cur,category.id])} aria-expanded={open} aria-controls={`${category.id}-items`}><span className="category-icon"><Icon size={18}/></span><span className="category-copy"><strong>{category.title}</strong><small>{categoryDone} von {category.items.length} erlebt</small><i><i style={{width:`${categoryDone/category.items.length*100}%`}}/></i></span><ChevronDown className={open?"chevron open":"chevron"}/></button><AnimatePresence initial={false}>{open&&<motion.div id={`${category.id}-items`} className="bucket-items" initial={reduced?false:{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}} transition={{duration:motionTokens.duration.normal,ease:motionTokens.ease.standard}}>{visible.length?visible.map(item=>{const checked=completedSet.has(item.id);return <motion.label layout className={checked?"bucket-item completed":"bucket-item"} key={item.id}><input type="checkbox" checked={checked} onChange={()=>toggle(item.id)}/><span className="custom-check" aria-hidden="true"><Check size={14}/></span><span>{item.text}</span></motion.label>}):<p className="empty-filter">In dieser Kategorie gibt es für diesen Filter noch keine Einträge.</p>}</motion.div>}</AnimatePresence></article>})}</div></section>
}
