"use client";
import Image from "next/image";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { Heart, Menu, Music, Pause, X, ChevronLeft, ChevronRight, Sparkles, Volume2 } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { loveStory, type Memory } from "@/data/loveStory";
import BucketList from "@/components/BucketList";
import { useRelationshipDuration } from "@/hooks/useRelationshipDuration";
import { imageRevealVariants, motionTokens, revealVariants, staggerVariants } from "@/lib/motion";
const nav=[["home","Anfang"],["story","Unsere Geschichte"],["reasons","Warum du"],["memories","Erinnerungen"],["bucket-list","Unsere Liste"],["letter","Mein Brief"],["future","Unsere Zukunft"]] as const;
function Reveal({children,className="",image=false}:{children:React.ReactNode;className?:string;image?:boolean}){const reduced=useReducedMotion();return <motion.div className={className} variants={image?imageRevealVariants:revealVariants} initial={reduced?false:"hidden"} whileInView="visible" viewport={{once:true,amount:.12}}>{children}</motion.div>}
function Photo({memory,priority=false,onClick,hero=false}:{memory:Memory;priority?:boolean;onClick:()=>void;hero?:boolean}){const [failed,setFailed]=useState(false);return <motion.button whileHover={{y:-3}} whileTap={{scale:.99}} className="memory" onClick={onClick} aria-label={`${memory.caption} öffnen`}>{!failed?<Image src={memory.src} alt={memory.alt} fill sizes="(max-width: 768px) 92vw, 42vw" priority={priority} onError={()=>setFailed(true)}/>:<span className="photo-fallback"><span>J / N</span><small>Hier darf eure Erinnerung einziehen</small></span>}<span className="memory-shade"/><span className="caption"><em>{memory.date}</em>{memory.caption}</span>{hero&&<span className="photo-monogram">J + N</span>}</motion.button>}
function Counter(){const d=useRelationshipDuration(loveStory.relationshipStart);const labels=[["Jahre",d?.years],["Monate",d?.months],["Tage",d?.days],["Stunden",d?.hours],["Minuten",d?.minutes],["Sekunden",d?.seconds],["Millisekunden",d?.milliseconds]];return <section className="counter-wrap" aria-labelledby="counter-title"><Reveal><p className="kicker">Zeit, die sich nach Zuhause anfühlt</p><h2 id="counter-title">So lange gibt es uns schon.</h2><p>Und es fühlt sich trotzdem erst wie der Anfang an.</p></Reveal><div className="counter">{labels.map(([label,value])=><div key={String(label)} className={label==="Millisekunden"?"milliseconds":""}><strong>{d?String(value).padStart(label==="Millisekunden"?3:2,"0"):"–"}</strong><span>{label}</span></div>)}</div></section>}
function Lightbox({index,close,setIndex}:{index:number;close:()=>void;setIndex:(n:number)=>void}){const ref=useRef<HTMLButtonElement>(null),m=loveStory.memories[index];useEffect(()=>{ref.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==="Escape")close();if(e.key==="ArrowLeft")setIndex((index-1+loveStory.memories.length)%loveStory.memories.length);if(e.key==="ArrowRight")setIndex((index+1)%loveStory.memories.length)};document.addEventListener("keydown",key);const overflow=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",key);document.body.style.overflow=overflow}},[close,index,setIndex]);return <motion.div className="lightbox" role="dialog" aria-modal="true" aria-label="Erinnerung vergrößert" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={e=>e.target===e.currentTarget&&close()}><button ref={ref} className="icon-button close" onClick={close} aria-label="Lightbox schließen"><X/></button><button className="icon-button prev" onClick={()=>setIndex((index-1+loveStory.memories.length)%loveStory.memories.length)} aria-label="Vorheriges Bild"><ChevronLeft/></button><motion.figure layoutId={`memory-${index}`} initial={{scale:.97}} animate={{scale:1}}><div className="lightbox-image"><Image src={m.src} alt={m.alt} fill sizes="90vw" unoptimized/></div><figcaption><span>{m.date} · {m.location}</span>{m.caption}</figcaption></motion.figure><button className="icon-button next" onClick={()=>setIndex((index+1)%loveStory.memories.length)} aria-label="Nächstes Bild"><ChevronRight/></button></motion.div>}
export default function Experience(){const [opened,setOpened]=useState(false),[menu,setMenu]=useState(false),[music,setMusic]=useState(false),[lightbox,setLightbox]=useState<number|null>(null),[message,setMessage]=useState(""),[final,setFinal]=useState(false),[heart,setHeart]=useState(0),[secret,setSecret]=useState(false);const audio=useRef<HTMLAudioElement>(null),trigger=useRef<HTMLButtonElement>(null);const reduced=useReducedMotion();const play=async()=>{try{if(audio.current){audio.current.volume=.18;await audio.current.play();setMusic(true)}}catch{setMusic(false)}};const open=()=>{setOpened(true);window.setTimeout(()=>document.getElementById("home")?.focus(),350);void play()};useEffect(()=>{let keys="";const f=(e:KeyboardEvent)=>{if(e.key.length===1){keys=(keys+e.key.toLowerCase()).slice(-5);if(keys==="nadia")setSecret(true)}};window.addEventListener("keydown",f);return()=>window.removeEventListener("keydown",f)},[]);useEffect(()=>()=>audio.current?.pause(),[]);const showMessage=()=>setMessage(p=>{const options=loveStory.messages.filter(x=>x!==p);return options[Math.floor(Math.random()*options.length)]});
return <><audio ref={audio} src={loveStory.musicPath} loop preload="none"/><AnimatePresence>{!opened&&<motion.section className="intro" exit={{opacity:0,scale:1.015,filter:"blur(5px)"}} transition={{duration:motionTokens.duration.cinematic,ease:motionTokens.ease.soft}}><div className="intro-orb"/><div className="intro-line"/><div className="intro-particles" aria-hidden="true"><i/><i/><i/><i/></div><motion.div variants={staggerVariants} initial="hidden" animate="visible"><motion.p className="kicker" variants={revealVariants}>{loveStory.intro.eyebrow}</motion.p><motion.h1 variants={revealVariants}>{loveStory.intro.title}</motion.h1><motion.p variants={revealVariants}>{loveStory.intro.text}</motion.p><motion.button variants={revealVariants} whileHover={{y:-2}} whileTap={{scale:.98}} className="opening-button" onClick={open}>{loveStory.intro.button}<span>→</span></motion.button><motion.button variants={revealVariants} className="skip" onClick={open}>Intro überspringen</motion.button></motion.div></motion.section>}</AnimatePresence>
<div className={opened?"site ready":"site"} aria-hidden={!opened}><div className="grain"/><div className="vignette"/><div className="ambient" aria-hidden="true"><i/><i/><i/><i/><i/></div><header><a className="monogram" href="#home" aria-label="Zum Anfang">J<span>+</span>N</a><nav aria-label="Hauptnavigation" className={menu?"open":""}>{nav.map(([id,label])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{label}</a>)}</nav><button className="icon-button menu-button" onClick={()=>setMenu(!menu)} aria-label="Navigation öffnen" aria-expanded={menu}><Menu/></button></header><button className="music-control" onClick={()=>music?(audio.current?.pause(),setMusic(false)):void play()} aria-label={music?"Musik pausieren":"Musik starten"}>{music?<Volume2 size={16}/>:<Music size={16}/>}<span>Musik</span>{music&&<i className="waves"/>}</button>
<main><section id="home" tabIndex={-1} className="hero"><svg className="hero-thread" viewBox="0 0 900 600" aria-hidden="true"><path d="M0,470 C180,330 260,530 450,360 S700,240 900,120"/></svg><div className="hero-copy"><Reveal><p className="kicker">Für Nadia, von Jakob</p><h1><span>Nadia,</span> du bist mein <em>Lieblingsmensch.</em></h1><p className="lead">{loveStory.hero.lead}</p><p className="muted">{loveStory.hero.body}</p><a className="text-link" href="#story">Unsere Geschichte entdecken <span>↓</span></a></Reveal></div><Reveal image className="hero-photo"><Photo hero memory={{src:loveStory.hero.image,alt:"Gemeinsames Foto von Nadia und Jakob",caption:"Hier beginnt eure Bildgeschichte."}} priority onClick={()=>{}}/></Reveal><a className="scroll-cue" href="#story" aria-label="Zur Geschichte scrollen"><span/>Scrollen</a></section><Counter/>
<section id="story" className="section story"><Reveal><p className="kicker">Kapitel 01</p><h2>Unsere Geschichte ist nicht laut. Aber sie bedeutet mir alles.</h2></Reveal><div className="timeline">{loveStory.timeline.map((e,i)=><Reveal key={e.title} className={`timeline-entry ${i%2?"right":""}`}><div className="dot"/><p className="date">{e.date}</p><h3>{e.title}</h3><p>{e.description}</p></Reveal>)}</div></section>
<section id="reasons" className="section reasons"><Reveal><p className="kicker">Warum du</p><h2>Sechzehn kleine Antworten auf eine große Frage.</h2></Reveal><div className="reasons-field">{loveStory.reasons.map((r,i)=><Reveal key={r} className={`reason reason-${i%5}`}><span>{String(i+1).padStart(2,"0")}</span><p>{r}</p></Reveal>)}</div></section>
<section id="memories" className="section memories"><Reveal><p className="kicker">Ein Archiv für uns</p><h2>Manche Fotos halten einen Moment fest. Andere ein ganzes Gefühl.</h2></Reveal><div className="gallery">{loveStory.memories.map((m,i)=><Reveal image key={m.src} className={`gallery-item item-${i}`}><motion.div layoutId={`memory-${i}`} className="gallery-frame"><Photo memory={m} onClick={()=>setLightbox(i)}/></motion.div></Reveal>)}</div></section><BucketList/>
<section id="letter" className="letter"><Reveal><p className="kicker">Ein Brief, nur für dich</p><article>{loveStory.letter.map((p,i)=><p key={p} className={i===0?"salutation":""}>{p}</p>)}<p className="signature">Jakob</p></article></Reveal></section>
<section id="future" className="section future"><Reveal><p className="kicker">Was vor uns liegt</p><h2>Kein großer Plan. Nur viele schöne Möglichkeiten, die ich gern mit dir erleben möchte.</h2></Reveal><div className="route">{loveStory.future.map((x,i)=><Reveal key={x} className="route-stop"><span>{i+1}</span><p>{x}</p></Reveal>)}</div><div className="surprises"><button className="outlined" onClick={()=>setSecret(true)}>Noch eine Sache …</button><button className="text-link" onClick={showMessage}>Eine Nachricht für dich <Sparkles size={15}/></button>{message&&<p className="message" role="status">{message}</p>}</div></section>
<section className={final?"final warm":"final"}><div className="final-thread" aria-hidden="true"><svg viewBox="0 0 500 250"><path d="M15 120 C70 55 135 65 160 120 C190 55 250 55 280 120 C315 180 395 175 480 80"/></svg></div><div className="final-particles">{final&&Array.from({length:12},(_,i)=><i key={i}/>)}</div><Reveal><p className="kicker">Das Ende dieser Seite. Nicht von uns.</p><h2>{loveStory.final.title}</h2><p className="declaration">{loveStory.final.declaration}</p><motion.button whileTap={{scale:.98}} className="opening-button" onClick={()=>setFinal(true)} disabled={final}>Und wie sehr? <Heart size={16}/></motion.button><AnimatePresence>{final&&<motion.p className="answer" initial={reduced?{opacity:0}:{opacity:0,y:12,filter:"blur(6px)"}} animate={{opacity:1,y:0,filter:"blur(0px)"}}>{loveStory.final.answer}</motion.p>}</AnimatePresence><p className="from">Für Nadia. Von Jakob.<br/>Seit dem 11.05.2025.</p><button ref={trigger} className="hidden-heart" onClick={()=>setHeart(c=>{const n=c+1;if(n>=5){setSecret(true);return 0}window.setTimeout(()=>setHeart(0),1800);return n})} aria-label="Eine kleine Überraschung finden"><Heart size={13}/></button></Reveal></section></main></div>
<AnimatePresence>{lightbox!==null&&<Lightbox index={lightbox} close={()=>{setLightbox(null);trigger.current?.focus()}} setIndex={setLightbox}/>} {secret&&<motion.div className="secret-modal" role="dialog" aria-modal="true" aria-labelledby="secret-title" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div initial={{scale:.97}} animate={{scale:1}}><button className="icon-button close" onClick={()=>setSecret(false)} aria-label="Nachricht schließen"><X/></button><Heart/><h2 id="secret-title">Du hast mein Herz sowieso schon längst gefunden.</h2><p>Falls du dich jemals fragst, ob ich dich liebe: Ja. Sehr.</p><small>Tipp für später: Schreibe einfach „nadia“ auf deiner Tastatur.</small></motion.div></motion.div>}</AnimatePresence></>}
